const loci = {
  'box 4': { locus: 'box 3' },
  'box 5': { locus: 'box 3' },
  'eurorack module boxes': { locus: 'box 1' },
  'cream chargers, nitrous oxide': { locus: 'box 2' },
  'kizer hic-cup box and accessories': { locus: 'box 2' },
  'eero wifi extender': { locus: 'box 2' },
  't12 soldering iron tip': { locus: 'box 2' },
  'pro-micro usb-c keyboard MCU board - in a mints tin': { locus: 'box 2' },
  'lokko lock picking kit': { locus: 'box 2' },
  'crkt fixed blade sheeth': { locus: 'box 2' },
  'whipping siphon tips': { locus: 'box 2' },
  '5pc rotary encoders w/ push': { locus: 'box 4' },
  '1/8 TS jacks PCB mount': { locus: 'box 4' },
  '1/8 TS jack bolts standard zinc': { locus: 'box 4' },
  '5x2 eurorack male ribbon headers': { locus: 'box 4' },
  'small black aluminum knobs with line indicator': { locus: 'box 4' },
  'buttons; tactile momentary plastic colored PCB mount ': { locus: 'box 4' },
  '4040 rectifier diodes': { locus: 'box 4' },
  'thumb screws; large blue red aluminum m3 eurorack': { locus: 'box 4' },
  '1/8 TS jack bolts - purple': { locus: 'box 4' },
  '1/8 TS jack bolts - orange': { locus: 'box 4' },
  'potentiometer mounting bolts': { locus: 'box 4' },
  '5x2 tall stood-off pin header female; small spacing': { locus: 'box 4' },
  'wall hooks from ikea': { locus: 'box 5' },
  'worksharp sharpening kit': { locus: 'box 3' },
  'white delrin trackball for ploopy': { locus: 'box 5' },
  'keychain keyring clips': { locus: 'box 5' },
  'abloy discus padlock key': { locus: 'box 5' },
  'choc switches spare black blue and robin': { locus: 'box 5' },
  'scottie dog trinket': { locus: 'box 5' },
  'befaco 1/8 nut wrench': { locus: 'box 5' },
  'deep blue automatic dive watch': { locus: 'box 5' },
  'whittling carving pocket knife': { locus: 'metal trinket box' },
  '32gb sd card': { locus: 'metal trinket box' },
  'logitech unifying receivers': { locus: 'metal trinket box' },
  'basic nail clippers': { locus: 'metal trinket box' },
  'metal switch puller': { locus: 'metal trinket box' },
  'sim card ejectors': { locus: 'metal trinket box' },
  'plastic switch puller': { locus: 'metal trinket box' },
  '1/8 to 1/4 trs adapter': { locus: 'metal trinket box' },
  '4 pin locking barrel plug and jack': { locus: 'metal trinket box' },
  'micro sd to sd adapter': { locus: 'metal trinket box' },
  'guitar picks': { locus: 'metal trinket box' },
  '16gb usb3.1 type a stick': { locus: 'metal trinket box' },
  '32gb usb3.0 type a stick': { locus: 'metal trinket box' },
  'art dj pre 2 phono preamp': { locus: 'box 3' },
  'toslink to rca stereo dac': { locus: 'box 3' },
  'stanley multitool': { locus: 'box 3' },
  'precision files': { locus: 'box 3' },
  'blink hub and accesories': { locus: 'box 6' },
  'mini phone tripod': { locus: 'box 6' },
  'desktop mic stand': { locus: 'box 6' },
  'electrical tape': { locus: 'box 6' },
  'tape measurer': { locus: 'box 6' },
  'usb c a adapters': { locus: 'box 6' },
  'akg pencil condensor microphone': { locus: 'box 6' },
  'brass standoffs m3': { locus: 'box 7' },
  'wood double stack knobs': { locus: 'box 7' },
  '1 inch oled screens': { locus: 'box 7' },
  'hiox crank manual coffee grinder': { locus: 'box 7' },
  'pcb mount alpha potentiometers b10k': { locus: 'box 7' },
  '1u not intellij format mixer module': { locus: 'box 7' },
  'iec 3 prong mount power inlet jack with switch': { locus: 'box 7' },
}
