const loci = {
  'box 4': { locus: 'box 3' },
  'box 5': { locus: 'box 3' },
  'eurorack module boxes': { locus: 'box 1' },
  'cream chargers, nitrous oxide': { locus: 'box 2' },
  'kizer hic-cup box and accessories': { locus: 'box 2' },
  'eero wifi extender': { locus: 'box 2' },
  't12 soldering iron tip': { locus: 'box 2' },
  'pro-micro usb-c keyboard MCU board - in a mints tin': { locus: 'box 2' },
  'lokko lock picking kit': { locus: 'box 2' },
  'crkt fixed blade sheeth': { locus: 'box 2' },
  'whipping siphon tips': { locus: 'box 2' },
  '5pc rotary encoders w/ push': { locus: 'box 4' },
  '1/8 TS jacks PCB mount': { locus: 'box 4' },
  '1/8 TS jack bolts standard zinc': { locus: 'box 4' },
  '5x2 eurorack male ribbon headers': { locus: 'box 4' },
  'small black aluminum knobs with line indicator': { locus: 'box 4' },
  'buttons; tactile momentary plastic colored PCB mount ': { locus: 'box 4' },
  '4040 rectifier diodes': { locus: 'box 4' },
  'thumb screws; large blue red aluminum m3 eurorack': { locus: 'box 4' },
  '1/8 TS jack bolts - purple': { locus: 'box 4' },
  '1/8 TS jack bolts - orange': { locus: 'box 4' },
  'potentiometer mounting bolts': { locus: 'box 4' },
  '5x2 tall stood-off pin header female; small spacing': { locus: 'box 4' },
  'wall hooks from ikea': { locus: 'box 5' },
  'worksharp sharpening kit': { locus: 'box 3' },
  'white delrin trackball for ploopy': { locus: 'box 5' },
  'keychain keyring clips': { locus: 'box 5' },
  'abloy discus padlock key': { locus: 'box 5' },
  'choc switches spare black blue and robin': { locus: 'box 5' },
  'scottie dog trinket': { locus: 'box 5' },
  'befaco 1/8 nut wrench': { locus: 'box 5' },
  'deep blue automatic dive watch': { locus: 'box 5' },
  'whittling carving pocket knife': { locus: 'metal trinket box' },
  '32gb sd card': { locus: 'metal trinket box' },
  'logitech unifying receivers': { locus: 'metal trinket box' },
  'basic nail clippers': { locus: 'metal trinket box' },
  'metal switch puller': { locus: 'metal trinket box' },
  'sim card ejectors': { locus: 'metal trinket box' },
  'plastic switch puller': { locus: 'metal trinket box' },
  '1/8 to 1/4 trs adapter': { locus: 'metal trinket box' },
  '4 pin locking barrel plug and jack': { locus: 'metal trinket box' },
  'micro sd to sd adapter': { locus: 'metal trinket box' },
  'guitar picks': { locus: 'metal trinket box' },
  '16gb usb3.1 type a stick': { locus: 'metal trinket box' },
  '32gb usb3.0 type a stick': { locus: 'metal trinket box' },
  'art dj pre 2 phono preamp': { locus: 'box 3' },
  'toslink to rca stereo dac': { locus: 'box 3' },
  'stanley multitool': { locus: 'box 3' },
  'precision files': { locus: 'box 3' },
  'blink hub and accesories': { locus: 'box 6' },
  'mini phone tripod': { locus: 'box 6' },
  'desktop mic stand': { locus: 'box 6' },
  'electrical tape': { locus: 'box 6' },
  'tape measurer': { locus: 'box 6' },
  'usb c a adapters': { locus: 'box 6' },
  'akg pencil condensor microphone': { locus: 'box 6' },
  'brass standoffs m3': { locus: 'box 7' },
  'wood double stack knobs': { locus: 'box 7' },
  '1 inch oled screens': { locus: 'box 7' },
  'hiox crank manual coffee grinder': { locus: 'box 7' },
  'pcb mount alpha potentiometers b10k': { locus: 'box 7' },
  '1u not intellij format mixer module': { locus: 'box 7' },
  'iec 3 prong mount power inlet jack with switch': { locus: 'box 7' },
  'guitar strings - nyxl 10-46': { locus: 'box 8' },
  'fader potentiometers': { locus: 'box 8' },
  'oscilloscope probes - cheap': { locus: 'box 8' },
  'oscilloscope probe - bnc to red and black alligator clip': {
    locus: 'box 8',
  },
  'aluminum pencil style cap puller': { locus: 'box 8' },
  'key switches - boba lt nixdork 65 purple and pink': { locus: 'box 8' },
  'countersunk flathead phillips screws - m2 m2.5 m3': { locus: 'box 8' },
  'joycon replacement joysticks': { locus: 'box 8' },
  'xacto blade - unopened': { locus: 'box 8' },
  'white led arcade button': { locus: 'box 8' },
  'gold banana jacks screw terminal': { locus: 'box 8' },
  'logitech pro receiver': { locus: 'box 8' },
  'velcro cable ties': { locus: 'box 8' },
  'aluminum knurled knob 20mm dia.': { locus: 'box 8', count: 4 },
  'xacto replacement blades': { locus: 'box 8', count: 10 },
  'arturia rackbrute red knob screw': { locus: 'box 8', count: 2 },
  'hackrf one sdr plexi case': { locus: 'box 8', count: 1 },
  'apple watch bands': { locus: 'box 8', count: 3 },
  'aluminum switch puller - long': { locus: 'box 8', count: 1 },
  'hakko replacement wedge tip': { locus: 'box 8', count: 1 },
  'PCB stripboard': { locus: 'box 8', count: 9 },
  't12 soldering tip - wedge': { locus: 'box 8', count: 1 },
  'barrel cjack to srew terminal adapter': { locus: 'box 8', count: 1 },
  '90 degree 1/8 trrs adapter': [
    { locus: 'box 8', count: 1 },
    { locus: 'box 9', count: 2 },
  ],
  deoxit: { locus: 'box 8', count: 1 },
  'functioning buff mult pcb - no panel or jacks': { locus: 'box 8', count: 1 },
  'hackrf one antenna - telescoping': { locus: 'box 8', count: 2 },
  'siam modular eurorack proto board': { locus: 'box 8', count: 6 },
  "'joycon to controller' adapter + charging dock": {
    locus: 'box 8',
    count: 1,
  },
  'orcas keyboard wrist rest': { locus: 'box 8', count: 1 },
  'multimeter leads pvc': { locus: 'box 8', count: 1 },
  'very large curved tophat aluminum knob with circle indicator': {
    locus: 'box 8',
    count: 1,
  },
  'wireless mouse - no battery cover - aa': { locus: 'box 8', count: 1 },
  'galaxie 500 emblems': { locus: 'box 8', count: 2 },
  'transistors - various': { locus: 'box 8', count: 300 },
  'nylon bristle brush - painter style': { locus: 'box 8', count: 1 },
  '22 awg wire spools - various': { locus: 'box 8', count: 3 },
  'crkbd corne oled covers - acrylic': { locus: 'box 8', count: 2 },
  'mini bic lighter': { locus: 'box 8', count: 1 },
  'headphone eartips - various sizes foam and silicone': {
    locus: 'box 8',
    count: 10,
  },
  'lithium ion battery 100mah 3.7v': { locus: 'box 8', count: 2 },
  'many format media card to usb a adapter': { locus: 'box 8', count: 1 },
  'gray trackball for mx ergo': { locus: 'box 8', count: 1 },
  'sennheiser e835 microphone': { locus: 'box 9', count: 1 },
  'fosi audio tda7498e mini power amplifier': { locus: 'box 9', count: 1 },
  '19" rack nuts': { locus: 'box 9', count: 4 },
  'black fountain ink refill': { locus: 'box 9', count: 2 },
  'adhesive cable tie strap': { locus: 'box 9', count: 4 },
  'solder wick': { locus: 'box 9', count: 2 },
  'aligator clip cable white': { locus: 'box 9', count: 1 },
  'cassette tapes': { locus: 'box 9', count: 5 },
  'olympus mini film camera': { locus: 'box 9', count: 1 },
  'oscilloscope probe accessories': { locus: 'box 9', count: 1 },
  'bracket for 60s corvetter radio amplifier': { locus: 'box 9', count: 1 },
  'multimeter alligator clip adaptor': { locus: 'box 9', count: 2 },
  'juul usb charging adapter': { locus: 'box 9', count: 2 },
  nerdwax: { locus: 'box 9', count: 2 },
  '3d printed skull pencil holder': { locus: 'box 9', count: 1 },
  'kershaw fixed blade knife sheeth': { locus: 'box 9', count: 1 },
  '10k knurled shaft potentiometer with knobs kit': {
    locus: 'box 9',
    count: 1,
  },
  'green trackball for mx ergo': { locus: 'box 9', count: 1 },
  '5v 1a usb a charger': { locus: 'box 9', count: 1 },
  '': { locus: 'box 9', count: 1 },
  '': { locus: 'box 9', count: 1 },
  '': { locus: 'box 9', count: 1 },
  '': { locus: 'box 9', count: 1 },
  '': { locus: 'box 9', count: 1 },
  '': { locus: 'box 9', count: 1 },
}

module.exports = loci
